import { API_URL, CLIENT_SECRET, ENCRYPTION_KEY, ENCRYPTION_VERSION, ENCRYPTION_MAGIC } from '@env';

export default {
  API_URL,
  CLIENT_SECRET,
  ENCRYPTION_KEY,
  ENCRYPTION_VERSION,
  ENCRYPTION_MAGIC,
  MAX_PULL_TIME: 120,
  BEARER_EXPIRE_TIME: 3600,
  TEST_MODE_STORAGE_KEY: '@settings/testURL',
};
